kind: Deployment
apiVersion: apps/v1
metadata:
  name: financial
  namespace: virtualyou
spec:
  replicas: 1
  selector:
    matchLabels:
      app: financial
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: financial
    spec:
      containers:
        - name: financial
          image: docker.virtualyou.info/financial:0.1.1
          env:
            - name: USERAUTH_SERVER_PORT_URL
              value: https://userauth.virtualyou.info
            - name: DB_HOST
              value: mariadb.mariadb.svc.cluster.local
            - name: DB_USERNAME
              value: 
            - name: DB_SCHEMA
              value: 
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: 
                  name: 
